#!/bin/bash
chmod +x data/powertop_tunables
sudo cp -n data/powertop.service /etc/systemd/system/ && 
sudo cp -n data/powertop_tunables.service /etc/systemd/system && 
sudo cp -n data/powertop.conf /etc && 
sudo cp -n data/powertop_tunables /usr/local/bin
sudo systemctl daemon-reload 
sudo systemctl enable powertop.service
sudo systemctl enable powertop_tunables.service
sudo updatedb
sudo systemctl start powertop.service
sudo systemctl start powertop_tunables.service
exit 0
